### ISSUE TITLE
Don't switch on runtimeType

### ISSUE THREAD

**Issue by ChristianKleineidam** [williambarreiro/clean-code-dart-en#2]
Switching on runtimeType is bad. If a new DartDeveloper class would be added that subclasses Developer your code would stop working. You violate the Liskov Substitution Principle.

Till we have pattern matching you need to do:
if (employee is Manager){
 ...
}
else if ( employee is Developer{
  ...
}

**Comment by williambarreiro** [comment]
Fair enough. Thanks @ChristianKleineidam!!
It's done on #4
